export default {
  MOVIES: "MOVIES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGLE_LOADER: "TOGGLE_LOADER",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  TOOGLE_SEARC: "TOOGLE_SEARC",
  SHOW_TOAST_NOTIFI: "SHOW_TOAST_NOTIFI",
};
